#!/usr/bin/env python3
"""
OpenCode integration for AI BGM.

OpenCode does not support declarative lifecycle hooks in its config.
Instead, it provides a plugin system (JS/TS modules) that can subscribe
to events. This integration generates a lightweight JS plugin file.
"""

from pathlib import Path
from typing import Tuple

from mythril_agent_bgm.commands.integrations import AIToolIntegration

_PLUGIN_TEMPLATE = """\
// Auto-generated by AI BGM (https://github.com/anthropics/mythril-agent-bgm)
// Re-run `bgm setup` to regenerate.

export const BGMPlugin = async ({ $ }) => {
  let currentSessionID = null;
  let isWorking = false;
  let lastIdleTime = 0;

  const DEBOUNCE_MS = 2000;

  // Helper to safely execute bgm commands (fire-and-forget)
  const runBgm = (cmd) => {
    $`bgm ${cmd}`.quiet().nothrow().catch(() => {});
  };

  return {
    event: async ({ event }) => {
      const props = event.properties;

      switch (event.type) {
        case "session.created":
          currentSessionID = props?.info?.id ?? null;
          isWorking = false;
          lastIdleTime = 0;
          break;

        case "message.updated":
          // Work on any user message (session ID check removed due to opencode bug #14808)
          if (
            !isWorking &&
            props?.info?.role === "user" &&
            Date.now() - lastIdleTime > DEBOUNCE_MS
          ) {
            isWorking = true;
            runBgm("play work 0");
          }
          break;

        case "session.idle":
          if (isWorking) {
            isWorking = false;
            lastIdleTime = Date.now();
            runBgm("play done");
          }
          break;

        case "session.deleted":
          isWorking = false;
          runBgm("stop");
          currentSessionID = null;
          break;
      }
    },

    "permission.ask": async () => {
      runBgm("play notification 0");
    },
  };
};
"""


class OpenCodeIntegration(AIToolIntegration):
    """Integration for OpenCode via plugin file."""

    def get_tool_info(self) -> Tuple[str, str]:
        """Get OpenCode tool information."""
        return ("opencode", "OpenCode")

    def get_settings_path(self) -> Path:
        """Get the plugin file path."""
        return Path.home() / ".config" / "opencode" / "plugins" / "opencode-bgm.js"

    def get_config_dir(self) -> Path:
        """OpenCode config root is ~/.config/opencode/, not the plugins/ subdirectory."""
        return Path.home() / ".config" / "opencode"

    def setup_hooks(self, settings: dict) -> dict:
        """Not used for OpenCode (plugin-based setup). Returns settings unchanged."""
        return settings

    def cleanup_hooks(self, settings: dict) -> dict:
        """Not used for OpenCode (plugin-based cleanup). Returns settings unchanged."""
        return settings

    def perform_setup(self) -> Tuple[bool, str]:
        """Write the BGM plugin JS file into OpenCode's plugin directory."""
        config_dir = self.get_config_dir()
        if not config_dir.exists():
            return (False, f"OpenCode: Config directory not found ({config_dir})")

        plugin_dir = self.get_settings_path().parent
        plugin_dir.mkdir(parents=True, exist_ok=True)

        self.get_settings_path().write_text(_PLUGIN_TEMPLATE, encoding="utf-8")
        return (True, "OpenCode: Plugin installed successfully [OK]")

    def perform_cleanup(self) -> Tuple[bool, str]:
        """Remove the BGM plugin JS file from OpenCode's plugin directory."""
        plugin_path = self.get_settings_path()
        if not plugin_path.exists():
            return (True, "OpenCode: No plugin file found, nothing to clean up")

        plugin_path.unlink()
        return (True, "OpenCode: Plugin removed successfully [OK]")
