#!/usr/bin/env python3
"""
Cline CLI integration for AI BGM.

Cline's CLI exposes a runtime hooks directory (``--hooks-dir``, default
``~/.cline/hooks``). Any executable script placed there and named after a
hook event is invoked by the CLI when that lifecycle event fires. This is
the non-plugin way to hook BGM into Cline CLI (there is also an SDK plugin
system, which this integration deliberately does NOT use).

Each hook script:
- receives a JSON payload on stdin
- prints ``{}`` on stdout ("no control changes")
- is named ``<Event>.sh`` and must be executable

Hooks installed by BGM:
- ``TaskStart.sh``       -> loop work music
- ``TaskComplete.sh``    -> play the done cue
- ``SessionShutdown.sh`` -> stop all music
- ``PostToolUse.sh``     -> play the notification sound when the agent asks
  the user a question (the ``ask_question`` tool, read from
  ``.tool_result.name``)

References:
- https://docs.cline.bot/cli/cli-reference.md (--hooks-dir)
- https://github.com/cline/cline/tree/main/sdk/examples/hooks
"""

import shutil
from pathlib import Path
from typing import Tuple

from mythril_agent_bgm.commands.integrations import AIToolIntegration

# Hook events we install. Must match Cline's runtime hook names.
_HOOK_EVENTS = ("TaskStart", "TaskComplete", "SessionShutdown", "PostToolUse")


class ClineIntegration(AIToolIntegration):
    """Integration for Cline CLI via runtime hook scripts in ~/.cline/hooks."""

    def get_tool_info(self) -> Tuple[str, str]:
        """Get Cline CLI tool information."""
        return ("cline", "Cline CLI")

    def get_settings_path(self) -> Path:
        """Get the Cline CLI runtime hooks directory."""
        return Path.home() / ".cline" / "hooks"

    def get_config_dir(self) -> Path:
        """Cline CLI config root used to detect whether Cline is installed."""
        return Path.home() / ".cline"

    def setup_hooks(self, settings: dict) -> dict:
        """Not used (script-based setup). Returns settings unchanged."""
        return settings

    def cleanup_hooks(self, settings: dict) -> dict:
        """Not used (script-based cleanup). Returns settings unchanged."""
        return settings

    def is_configured(self) -> bool:
        """BGM is configured iff every BGM hook script exists."""
        hooks_dir = self.get_settings_path()
        return all((hooks_dir / f"{event}.sh").exists() for event in _HOOK_EVENTS)

    def is_up_to_date(self) -> bool:
        """BGM is up to date iff every hook script exists with current content."""
        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return False
        hooks_dir = self.get_settings_path()
        for event in _HOOK_EVENTS:
            script = hooks_dir / f"{event}.sh"
            if not script.exists():
                return False
            if script.read_text(encoding="utf-8") != self._hook_script(event, bgm_path):
                return False
        return True

    def perform_setup(self) -> Tuple[bool, str]:
        """Write the BGM hook scripts into Cline's runtime hooks directory."""
        config_dir = self.get_config_dir()
        if not config_dir.exists():
            return (False, f"Cline CLI: Config directory not found ({config_dir})")

        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return (False, "Cline CLI: 'bgm' command not found in PATH")

        hooks_dir = self.get_settings_path()
        hooks_dir.mkdir(parents=True, exist_ok=True)

        for event in _HOOK_EVENTS:
            script = hooks_dir / f"{event}.sh"
            script.write_text(self._hook_script(event, bgm_path), encoding="utf-8")
            script.chmod(0o755)
        return (True, "Cline CLI: Hooks installed successfully [OK]")

    def perform_cleanup(self) -> Tuple[bool, str]:
        """Remove the BGM hook scripts from Cline's runtime hooks directory."""
        hooks_dir = self.get_settings_path()
        removed = False
        for event in _HOOK_EVENTS:
            script = hooks_dir / f"{event}.sh"
            if script.exists():
                script.unlink()
                removed = True
        if not removed:
            return (True, "Cline CLI: No BGM hooks found, nothing to clean up")
        return (True, "Cline CLI: Hooks removed successfully [OK]")

    @staticmethod
    def _hook_script(event: str, bgm_path: str) -> str:
        """Generate the shell hook script content for a given Cline event."""
        header = (
            "#!/usr/bin/env bash\n"
            "# Auto-generated by AI BGM (https://github.com/anthropics/mythril-agent-bgm).\n"
            "# Re-run `bgm setup` to regenerate.\n"
            "\n"
        )

        if event == "TaskStart":
            body = f'command -v "{bgm_path}" >/dev/null 2>&1 && "{bgm_path}" play work 0\n'
        elif event == "TaskComplete":
            body = f'command -v "{bgm_path}" >/dev/null 2>&1 && "{bgm_path}" play done\n'
        elif event == "SessionShutdown":
            body = f'command -v "{bgm_path}" >/dev/null 2>&1 && "{bgm_path}" stop\n'
        elif event == "PostToolUse":
            body = (
                'input=$(cat)\n'
                "tool=$(printf '%s' \"$input\" | jq -r '.tool_result.name // \"\"' 2>/dev/null)\n"
                'if [ "$tool" = "ask_question" ]; then\n'
                f'  command -v "{bgm_path}" >/dev/null 2>&1 && "{bgm_path}" play notification 0\n'
                "fi\n"
            )
        else:
            raise ValueError(f"Unknown Cline hook event: {event}")

        # An empty JSON object means "no control changes".
        return header + body + "echo '{}'\n"
