#!/usr/bin/env python3
"""
Pi Coding Agent (pi) integration for AI BGM.

Pi Coding Agent is a Node-based coding agent CLI + TUI whose global config
root lives at ``~/.pi/agent``. It has no declarative settings hooks; instead
its official extension mechanism auto-discovers ``~/.pi/agent/extensions/*.ts``
modules (loaded through jiti, hot-reloadable via ``/reload``). BGM hooks in by
writing a single generated extension file that subscribes to pi session events
(``agent_start`` / ``agent_end`` / ``tool_call`` / ``tool_result`` /
``session_shutdown``) and spawns the ``bgm`` CLI as a detached child process.

The generated extension is plain-JS-compatible ESM (types expressed as JSDoc
only, no TS annotations) so it stays loadable by jiti and passes ``node
--check``, and it swallows all spawn errors so an unavailable ``bgm`` can
never break a pi session.
"""

import json
import shutil
import time
from pathlib import Path
from typing import Tuple

from mythril_agent_bgm.commands.integrations import AIToolIntegration

# Generated extension file name inside ~/.pi/agent/extensions/.
_EXTENSION_NAME = "mythril-agent-bgm.ts"
# Backup name format for an existing extension overwritten by setup: the
# extension name, a unique timestamp, and the backup suffix, e.g.
# mythril-agent-bgm.ts.20260815123456.bak. The timestamp (plus an existence
# check in _get_backup_path) guarantees repeated setups never collide — a
# fixed ".bak" name would throw FileExistsError on Windows and silently
# overwrite the previous backup on POSIX.
_BACKUP_NAME_FORMAT = "{name}.{timestamp}.bak"
# Human-readable config root used in user-facing messages (paths are never
# hardcoded in the messages themselves).
_CONFIG_DIR_LABEL = "~/.pi/agent"

# Extension template. `__BGM_PATH_JSON__` is replaced at generation time with
# the json-escaped absolute bgm path (so paths with quotes/backslashes stay
# valid). The generated file is plain-JS-compatible ESM: JSDoc types only, no
# TS annotations, so jiti can load it and `node --check` accepts it.
_EXTENSION_TEMPLATE = """\
// Auto-generated by AI BGM (https://github.com/jie-meng/mythril-agent-bgm)
// Re-run `bgm setup` to regenerate.

import { spawn } from "node:child_process";

const BGM = __BGM_PATH_JSON__;

// Module-level bookkeeping: time of the last work-music start (gates the
// done cue so a session that never played work stays silent) and the tool
// call ids of question/ask-style tools still awaiting the user's answer.
let lastWorkTime = 0;
const pendingQuestions = new Set();

/** @param {import("@earendil-works/pi-coding-agent").ExtensionAPI} pi */
export default function (pi) {
  const run = (...args) => {
    const child = spawn(BGM, args, {
      stdio: "ignore",
      detached: true,
      windowsHide: true,
    });
    // bgm must never break a pi session: swallow async spawn failures
    // (e.g. ENOENT when the embedded bgm path is stale).
    child.on("error", () => {});
    child.unref();
  };

  // A real user prompt starts (or restarts) the work loop.
  pi.on("agent_start", () => {
    lastWorkTime = Date.now();
    run("play", "work", "0");
  });

  // Task finished: play the done cue, gated on work music having actually
  // played this session.
  pi.on("agent_end", () => {
    if (lastWorkTime > 0) {
      run("play", "done");
    }
  });

  // A question/ask-style tool is waiting on the user: play the notification
  // cue and reset the work marker so the answer restarts work music.
  pi.on("tool_call", (event) => {
    if (event.toolName === "question" || event.toolName?.startsWith("ask")) {
      pendingQuestions.add(event.toolCallId);
      lastWorkTime = 0;
      run("play", "notification", "0");
    }
  });

  // The user's answer to a pending question arrived: resume work music.
  pi.on("tool_result", (event) => {
    if (
      (event.toolName === "question" || event.toolName?.startsWith("ask")) &&
      pendingQuestions.delete(event.toolCallId)
    ) {
      lastWorkTime = Date.now();
      run("play", "work", "0");
    }
  });

  // Session over (quit / reload / new / resume / fork): clear bookkeeping
  // first, then stop the music.
  pi.on("session_shutdown", () => {
    pendingQuestions.clear();
    lastWorkTime = 0;
    run("stop");
  });
}
"""


class PiIntegration(AIToolIntegration):
    """Integration for Pi Coding Agent via a generated extension file."""

    def get_tool_info(self) -> Tuple[str, str]:
        """Get Pi Coding Agent tool information."""
        return ("pi", "Pi Coding Agent")

    def get_settings_path(self) -> Path:
        """Get the generated extension file path."""
        return Path.home() / ".pi" / "agent" / "extensions" / _EXTENSION_NAME

    def get_config_dir(self) -> Path:
        """pi config root used to detect whether pi is installed."""
        return Path.home() / ".pi" / "agent"

    def setup_hooks(self, settings: dict) -> dict:
        """Not used (extension-based setup). Returns settings unchanged."""
        return settings

    def cleanup_hooks(self, settings: dict) -> dict:
        """Not used (extension-based cleanup). Returns settings unchanged."""
        return settings

    def is_configured(self) -> bool:
        """BGM is configured iff the extension file exists."""
        try:
            return self.get_settings_path().exists()
        except OSError:
            return False

    def is_up_to_date(self) -> bool:
        """BGM is up to date iff the extension file matches generated content."""
        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return False
        extension_path = self.get_settings_path()
        if not extension_path.exists():
            return False
        try:
            return extension_path.read_text(encoding="utf-8") == self._generate_extension(bgm_path)
        except (OSError, UnicodeDecodeError):
            return False

    def perform_setup(self) -> Tuple[bool, str]:
        """Write the BGM extension into pi's global extension directory."""
        config_dir = self.get_config_dir()
        if not config_dir.exists():
            return (
                False,
                f"Pi Coding Agent: Config directory not found ({_CONFIG_DIR_LABEL}) — "
                f"run `pi` once to initialize",
            )

        bgm_path = shutil.which("bgm")
        if not bgm_path:
            return (False, "Pi Coding Agent: 'bgm' command not found in PATH")

        extension_path = self.get_settings_path()
        generated = self._generate_extension(bgm_path)
        try:
            if extension_path.exists():
                existing = extension_path.read_text(encoding="utf-8")
                if existing == generated:
                    return (
                        True,
                        "Pi Coding Agent: Extension already installed and up to date [OK] — "
                        "run `/reload` in pi (or restart pi) to activate",
                    )
                # An existing file with different content is backed up before
                # being overwritten so a user's manual edit is never lost; the
                # timestamped name keeps repeated setups collision-free.
                extension_path.rename(self._get_backup_path(extension_path))
            extension_path.parent.mkdir(parents=True, exist_ok=True)
            extension_path.write_text(generated, encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            return (False, f"Pi Coding Agent: Unable to write extension: {exc}")

        return (
            True,
            "Pi Coding Agent: Extension installed successfully [OK] — "
            "please run `/reload` in pi (or restart pi) to activate",
        )

    def perform_cleanup(self) -> Tuple[bool, str]:
        """Remove the BGM extension file from pi's extension directory."""
        extension_path = self.get_settings_path()
        if not extension_path.exists():
            return (True, "Pi Coding Agent: No extension file found, nothing to clean up")

        try:
            # A symlinked extension must be unlinked, not rmtree'd (rmtree on
            # a symlink raises OSError); unlink removes the link itself, never
            # the target it points to.
            extension_path.unlink()
        except OSError as exc:
            return (False, f"Pi Coding Agent: Unable to remove extension: {exc}")
        return (True, "Pi Coding Agent: Extension removed successfully [OK]")

    @staticmethod
    def _get_backup_path(extension_path: Path) -> Path:
        """Unique timestamped backup path for an existing extension file.

        Backups use a per-second timestamp (``mythril-agent-bgm.ts.<YYYYmmddHHMMSS>.bak``);
        if that name already exists (e.g. two setups within the same second)
        a numeric counter is appended so the backup never collides with a
        previous one on any platform.
        """
        timestamp = time.strftime("%Y%m%d%H%M%S")
        backup_path = extension_path.with_name(
            _BACKUP_NAME_FORMAT.format(name=extension_path.name, timestamp=timestamp)
        )
        counter = 1
        while backup_path.exists():
            backup_path = extension_path.with_name(
                f"{extension_path.name}.{timestamp}.{counter}.bak"
            )
            counter += 1
        return backup_path

    @staticmethod
    def _generate_extension(bgm_path: str) -> str:
        """Generate the extension content with the resolved bgm path embedded."""
        return _EXTENSION_TEMPLATE.replace("__BGM_PATH_JSON__", json.dumps(bgm_path))
